### ISSUE TITLE
Using System base types

### ISSUE THREAD

**Issue by zedr0n** [wirthma/CsStubsGenerator#2]
I've tried generating a stub for one of my libraries I use in another MPS project and it works fine for types defined in the library itself but any type which is from System.* is ignored. e.g

[class CsStubsGenerator.core.CsSingleMpsEntityGenerator] Parsing of type reference: MPS entity System-Boolean:System.Boolean was discovered to be a model and not a stub.

Am I missing something? Is it possible to reuse CSStdLibrary somehow?

**Comment by wirthma** [comment]
Hello zedr0n,

thank you for your interest in the *CsStubsGenerator* plugin.

Generating of stubs for libraries depending on other libraries (e.g. on the standard library) is problematic. The problem is that the plugin does not detect already existing stubs. Therefore your stubs are not connected with the stub for `System.Boolean` and therefore you experience the issue you posted.

Since there is no type system implemented for the C# base language, you may proceed even with these issues - just use the generated stubs as they were correctly constructed.

**Comment by zedr0n** [comment]
Thanks for your reply. Yeah, the issue is the types are all empty, I wonder if it would be better to set them to generictypereferencestring instead? that's what I normally do for when I don't have stubs

**Comment by wirthma** [comment]
Yes, that is possible - this gets you a properly generated C# source code at the end.

Basically, it should not be a problem to have your stubs with missing return types and so on. In your program that uses the stubs, you need only the names of the classes, methods, ... (because the C# base language is not fully implemented, e.g. type system is missing). So you do not have to correct the errors in the generated stubs in order to work with the stubs in your MPS program.

**Comment by wirthma** [comment]
In other words, stubs with errors should not prevent you from using them in some other MPS C# code. And if it would, in a scenario that I do not see right now, using `GenericTypeReferenceString` instead should help you.

**Comment by wirthma** [comment]
Another work-around would be to add the missing types manually into the XML stubs specification file you use as an input for this plugin. Just watch the XML structure and define your own `System.Boolean` there - this should work as well. But using `GenericTypeReferenceString` is probably more robust idea with respect to future possible improvements of the C# base language and related plugins...
